title: PRIMAVERA
description: PRIMAVERA is a Horizon 2020 project funded by European Commission. The project is a collaboration between 19 European partners, led by the Met Office and the Reading University in the UK.
show_excerpts: true
baseurl: /primavera-jekyll
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
